from src.world.map import HeightMap, SurfaceMap
from src.registry.registry import Registry

from os.path import abspath

height_maps = Registry[HeightMap]("vanilla")
surface_maps = Registry[SurfaceMap]("vanilla")


def get_height_location(planet_name: str):
    return abspath(f"../resources/assets/vanilla/planets/heights/{planet_name}_height.png")


def get_surface_location(planet_name: str):
    return abspath(f"../resources/assets/vanilla/planets/surfaces/{planet_name}_surface.png")


AJA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("aja", get_height_location("aja")))
ARANYANI_HEIGHT_MAP = height_maps.register(HeightMap.from_image("aranyani", get_height_location("aranyani")))
ARIEL_HEIGHT_MAP = height_maps.register(HeightMap.from_image("ariel", get_height_location("ariel")))
ASINTMAH_HEIGHT_MAP = height_maps.register(HeightMap.from_image("asintmah", get_height_location("asintmah")))
BACCHUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image("bacchus", get_height_location("bacchus")))
BOREAS_HEIGHT_MAP = height_maps.register(HeightMap.from_image("boreas", get_height_location("boreas")))
CALLISTO_HEIGHT_MAP = height_maps.register(HeightMap.from_image("callisto", get_height_location("callisto")))
CAMBRIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("cambria", get_height_location("cambria")))
CERES_HEIGHT_MAP = height_maps.register(HeightMap.from_image("ceres", get_height_location("ceres")))
CHARON_HEIGHT_MAP = height_maps.register(HeightMap.from_image("charon", get_height_location("charon")))
CHIBANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("chibania", get_height_location("chibania")))
CRETACEA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("cretacea", get_height_location("cretacea")))
DAMU_HEIGHT_MAP = height_maps.register(HeightMap.from_image("damu", get_height_location("damu")))
DANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("dania", get_height_location("dania")))
DIONE_HEIGHT_MAP = height_maps.register(HeightMap.from_image("dione", get_height_location("dione")))
EARTH_HEIGHT_MAP = height_maps.register(HeightMap.from_image("earth", get_height_location("earth")))
ERIS_HEIGHT_MAP = height_maps.register(HeightMap.from_image("eris", get_height_location("eris")))
EUROPA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("europa", get_height_location("europa")))
GANYMEDE_HEIGHT_MAP = height_maps.register(HeightMap.from_image("ganymede", get_height_location("ganymede")))
HUANCA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("huanca", get_height_location("huanca")))
IAPETUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image("iapetus", get_height_location("iapetus")))
IO_HEIGHT_MAP = height_maps.register(HeightMap.from_image("io", get_height_location("io")))
LETHE_HEIGHT_MAP = height_maps.register(HeightMap.from_image("lethe", get_height_location("lethe")))
MAKEMAKE_HEIGHT_MAP = height_maps.register(HeightMap.from_image("makemake", get_height_location("makemake")))
MARS_HEIGHT_MAP = height_maps.register(HeightMap.from_image("mars", get_height_location("mars")))
MERCURY_HEIGHT_MAP = height_maps.register(HeightMap.from_image("mercury", get_height_location("mercury")))
MIRANDA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("miranda", get_height_location("miranda")))
OBERON_HEIGHT_MAP = height_maps.register(HeightMap.from_image("oberon", get_height_location("oberon")))
OSTARA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("ostara", get_height_location("ostara")))
PLUTO_HEIGHT_MAP = height_maps.register(HeightMap.from_image("pluto", get_height_location("pluto")))
PONTUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image("pontus", get_height_location("pontus")))
RAGNAROK_HEIGHT_MAP = height_maps.register(HeightMap.from_image("ragnarok", get_height_location("ragnarok")))
RHEA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("rhea", get_height_location("rhea")))
RODINIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("rodinia", get_height_location("rodinia")))
RUAUMOKO_HEIGHT_MAP = height_maps.register(HeightMap.from_image("ruaumoko", get_height_location("ruaumoko")))
SEDNA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("sedna", get_height_location("sedna")))
TETHYS_HEIGHT_MAP = height_maps.register(HeightMap.from_image("tethys", get_height_location("tethys")))
TITANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("titania", get_height_location("titania")))
TITAN_HEIGHT_MAP = height_maps.register(HeightMap.from_image("titan", get_height_location("titan")))
TRITON_HEIGHT_MAP = height_maps.register(HeightMap.from_image("triton", get_height_location("triton")))
ULTIMA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("ultima", get_height_location("ultima")))
UMBRIEL_HEIGHT_MAP = height_maps.register(HeightMap.from_image("umbriel", get_height_location("umbriel")))
VAALBARA_HEIGHT_MAP = height_maps.register(HeightMap.from_image("vaalbara", get_height_location("vaalbara")))
VENUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image("venus", get_height_location("venus")))

AJA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("aja", get_surface_location("aja")))
ARANYANI_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("aranyani", get_surface_location("aranyani")))
ARIEL_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("ariel", get_surface_location("ariel")))
ASINTMAH_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("asintmah", get_surface_location("asintmah")))
BACCHUS_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("bacchus", get_surface_location("bacchus")))
BOREAS_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("boreas", get_surface_location("boreas")))
CALLISTO_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("callisto", get_surface_location("callisto")))
CAMBRIA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("cambria", get_surface_location("cambria")))
CERES_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("ceres", get_surface_location("ceres")))
CHARON_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("charon", get_surface_location("charon")))
CHIBANIA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("chibania", get_surface_location("chibania")))
CRETACEA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("cretacea", get_surface_location("cretacea")))
DAMU_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("damu", get_surface_location("damu")))
DANIA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("dania", get_surface_location("dania")))
DIONE_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("dione", get_surface_location("dione")))
EARTH_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("earth", get_surface_location("earth")))
ERIS_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("eris", get_surface_location("eris")))
EUROPA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("europa", get_surface_location("europa")))
GANYMEDE_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("ganymede", get_surface_location("ganymede")))
HUANCA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("huanca", get_surface_location("huanca")))
LAPETUS_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("lapetus", get_surface_location("lapetus")))
LETHE_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("lethe", get_surface_location("lethe")))
MAKEMAKE_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("makemake", get_surface_location("makemake")))
MARS_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("mars", get_surface_location("mars")))
MERCURY_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("mercury", get_surface_location("mercury")))
MIRANDA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("miranda", get_surface_location("miranda")))
MOON_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("moon", get_surface_location("moon")))
OBERON_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("oberon", get_surface_location("oberon")))
OSTARA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("ostara", get_surface_location("ostara")))
PLUTO_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("pluto", get_surface_location("pluto")))
PONTUS_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("pontus", get_surface_location("pontus")))
RAGNAROK_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("ragnarok", get_surface_location("ragnarok")))
RHEA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("rhea", get_surface_location("rhea")))
RODINIA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("rodinia", get_surface_location("rodinia")))
RUAOMOKO_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("ruaomoko", get_surface_location("ruaomoko")))
SEDNA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("sedna", get_surface_location("sedna")))
TETHYS_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("tethys", get_surface_location("tethys")))
TITANIA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("titania", get_surface_location("titania")))
TITAN_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("titan", get_surface_location("titan")))
TRITON_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("triton", get_surface_location("triton")))
ULTIMA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("ultima", get_surface_location("ultima")))
UMBRIEL_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("umbriel", get_surface_location("umbriel")))
VAALBARA_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("vaalbara", get_surface_location("vaalbara")))
VENUS_SURFACE_MAP = surface_maps.register(SurfaceMap.from_image("venus", get_surface_location("venus")))
