from map import HeightMap, SurfaceMap
from src.registry.registry import Registry, HEIGHT_MAP_REGISTRY, SURFACE_MAP_REGISTRY

height_maps = Registry(HEIGHT_MAP_REGISTRY, "vanilla")
surface_maps = Registry(SURFACE_MAP_REGISTRY, "vanilla")


def get_height_location(planet_name: str):
    return f"../../resources/assets/vanilla/planets/heights/{planet_name}_height.png"


AJA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
ARANYANI_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aranyani")))
ARIEL_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("ariel")))
ASINTMAH_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("asintmah")))
BACCHUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("bacchus")))
BOREAS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("boreas")))
CALLISTO_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("callisto")))
CAMBRIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("cambria")))
CERES_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("ceres")))
CHARON_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("charon")))
CHIBANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("chibania")))
CRETACEA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("cretacea")))
DAMU_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("damu")))
DANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("dania")))
DIONE_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("dione")))
EARTH_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("earth")))
ERIS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("eris")))
EUROPA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("europa")))
GANYMEDE_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("ganymede")))
HUANCA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("huanca")))
IAPETUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("iapetus")))
IO_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("io")))
LETHE_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("lethe")))
MAKEMAKE_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("makemake")))
MARS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("mars")))
MERCURY_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("mercury")))
MIRANDA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("miranda")))
OBERON_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("oberon")))
OSTARA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("ostara")))
PLUTO_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("pluto")))
PONTUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("pontus")))
RAGNAROK_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("ragnarok")))
RHEA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("rhea")))
RODINIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("rodinia")))
RUAUMOKO_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("ruaumoko")))
SEDNA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("sedna")))
TETHYS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("tethys")))
TITANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("titania")))
TITAN_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("titan")))
TRITON_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("triton")))
ULTIMA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("ultima")))
UMBRIEL_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("umbriel")))
VAALBARA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("vaalbara")))
VENUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("venus")))
