from src.world.map import HeightMap, SurfaceMap
from src.registry.registry import Registry

from os.path import abspath

height_maps = Registry[HeightMap]("vanilla")
surface_maps = Registry[SurfaceMap]("vanilla")


def get_height_location(planet_name: str):
    return abspath(f"../resources/assets/vanilla/planets/heights/{planet_name}_height.png")


AJA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
ARANYANI_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
ARIEL_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
ASINTMAH_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
BACCHUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
BOREAS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
CALLISTO_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
CAMBRIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
CERES_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
CHARON_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
CHIBANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
CRETACEA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
DAMU_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
DANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
DIONE_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
EARTH_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
ERIS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
EUROPA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
GANYMEDE_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
HUANCA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
IAPETUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
IO_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
LETHE_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
MAKEMAKE_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
MARS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
MERCURY_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
MIRANDA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
OBERON_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
OSTARA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
PLUTO_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
PONTUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
RAGNAROK_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
RHEA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
RODINIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
RUAUMOKO_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
SEDNA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
TETHYS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
TITANIA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
TITAN_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
TRITON_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
ULTIMA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
UMBRIEL_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
VAALBARA_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
VENUS_HEIGHT_MAP = height_maps.register(HeightMap.from_image(get_height_location("aja")))
